### ISSUE TITLE
风险询问

### ISSUE THREAD

**Issue by bingcheng1998** [danyang685/sjtuAixinwuFan#1]
请问`风险提醒：JASiteCookie数据的拥有者可完全控制此爱心屋账号。`是什么意思？

整个程序除了与爱心屋通讯还会与别的地址通讯，从而泄露jaccount账号吗？

**Comment by danyang685** [comment]
不是这样的，本程序本身不会将JASiteCookie数据发送给除爱心屋网站外的其他网站。
此程序中依靠爱心屋网站的一个Cookie——JASiteCookie来实现登录状态的保持。据观察，这个Cookie永远不会失效，因此一旦将这串代码告诉他人，便相当于将此爱心屋账号永远与别人分享，无法终止。
因此一旦通过js代码：`document.cookie.split('; ').forEach(function(c){if(c.includes('JASiteCookie'))console.error(c)})`
从浏览器导出了自己的JASiteCookie数据，就应当妥善保存，泄露此数据意味着爱心屋账号永远泄露。JASiteCookie数据的所有者是爱心屋网站，与JAccount无关，此数据只在爱心屋网站有效，不会导致JAccount信息泄露

**Comment by bingcheng1998** [comment]
谢谢你，经试验很好用，配合openmediavault自动任务，特别方便！

**Comment by danyang685** [comment]
谢谢
